# Generated by Django 5.2.5 on 2025-09-01 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Цитата')),
                ('source', models.CharField(max_length=100, verbose_name='Источник (фильм, книга)')),
                ('weight', models.PositiveIntegerField(default=1, verbose_name='Вес (шанс показа)')),
                ('likes', models.PositiveIntegerField(default=0, verbose_name='Лайки')),
                ('dislikes', models.PositiveIntegerField(default=0, verbose_name='Дизлайки')),
                ('view_count', models.PositiveIntegerField(default=0, verbose_name='Просмотры')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Цитата',
                'verbose_name_plural': 'Цитаты',
                'unique_together': {('text',)},
            },
        ),
    ]
